from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enrollment(object):
    def setupUi(self, Enrollment):

        # Main settings
        Enrollment.setObjectName("Enrollment")
        Enrollment.resize(991, 588)
        self.hL_Enrollment = QtWidgets.QHBoxLayout(Enrollment)
        self.hL_Enrollment.setObjectName("hL_Enrollment")
        self.widget_enr_input_box = QtWidgets.QWidget(Enrollment)
        self.widget_enr_input_box.setObjectName("widget_enr_input_box")
        self.vL_widget_enr_input_box = QtWidgets.QVBoxLayout(self.widget_enr_input_box)
        self.vL_widget_enr_input_box.setObjectName("vL_widget_enr_input_box")
        self.widget_enr_edit_buts = QtWidgets.QWidget(self.widget_enr_input_box)
        self.widget_enr_edit_buts.setObjectName("widget_enr_edit_buts")
        self.hL_widget_enr_edit_buts = QtWidgets.QHBoxLayout(self.widget_enr_edit_buts)
        self.hL_widget_enr_edit_buts.setObjectName("hL_widget_enr_edit_buts")

        self.pushButton_enr_save = QtWidgets.QPushButton(self.widget_enr_edit_buts)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_enr_save.setFont(font)
        self.pushButton_enr_save.setObjectName("pushButton_enr_save")
        self.hL_widget_enr_edit_buts.addWidget(self.pushButton_enr_save)

        self.vL_widget_enr_input_box.addWidget(self.widget_enr_edit_buts)

        # Group Box for Subjects
        self.groupBox_stud_subs = QtWidgets.QGroupBox(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_stud_subs.setFont(font)
        self.groupBox_stud_subs.setObjectName("groupBox_stud_subs")
        self.vL_groupBox_stud_subs = QtWidgets.QVBoxLayout(self.groupBox_stud_subs)
        self.vL_groupBox_stud_subs.setObjectName("vL_groupBox_stud_subs")

        # CheckBoxes for gB
        self.el_CheckBox_sub_1 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_1.setFont(font)
        self.el_CheckBox_sub_1.setObjectName("el_CheckBox_sub_1")
        self.vL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_1)
        self.el_CheckBox_sub_2 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_2.setFont(font)
        self.el_CheckBox_sub_2.setObjectName("el_CheckBox_sub_2")
        self.vL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_2)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)
        self.el_CheckBox_sub_3 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_3.setFont(font)
        self.el_CheckBox_sub_3.setObjectName("el_CheckBox_sub_3")
        self.vL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_3)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)
        self.el_CheckBox_sub_4 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_4.setFont(font)
        self.el_CheckBox_sub_4.setObjectName("el_CheckBox_sub_4")
        self.vL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_4)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)

        # GroupBox for Contacts Generator
        self.groupBox_sis_contracts = QtWidgets.QGroupBox(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_sis_contracts.setFont(font)
        self.groupBox_sis_contracts.setObjectName("groupBox_sis_contracts")
        self.vL_groupBox_sis_contracts = QtWidgets.QVBoxLayout(self.groupBox_sis_contracts)
        self.vL_groupBox_sis_contracts.setObjectName("vL_groupBox_sis_contracts")
        self.vL_widget_enr_input_box.addWidget(self.groupBox_sis_contracts)

        # GrB for Cont subjects
        self.grB_0 = QtWidgets.QGroupBox(self.groupBox_sis_contracts)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grB_0.setFont(font)
        self.grB_0.setObjectName("grB_0")
        self.gL_grB_0 = QtWidgets.QGridLayout(self.grB_0)
        self.gL_grB_0.setObjectName("gL_grB_0")
        self.vL_groupBox_sis_contracts.addWidget(self.grB_0)

        self.lab_num_0 = QtWidgets.QLabel(self.grB_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_num_0.setFont(font)
        self.lab_num_0.setObjectName("lab_num_0")
        self.gL_grB_0.addWidget(self.lab_num_0, 0, 0)

        self.lEdit_0 = QtWidgets.QLineEdit(self.grB_0)
        self.lEdit_0.setObjectName("lEdit_0")
        self.gL_grB_0.addWidget(self.lEdit_0, 0, 1)

        self.lab_date_0 = QtWidgets.QLabel(self.grB_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_date_0.setFont(font)
        self.lab_date_0.setObjectName("lab_date_0")
        self.gL_grB_0.addWidget(self.lab_date_0, 1, 0)

        self.dEdit_0 = QtWidgets.QDateEdit(self.grB_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dEdit_0.setFont(font)
        self.dEdit_0.setDate(QtCore.QDate(2000, 1, 1))
        self.dEdit_0.setObjectName("dEdit_0")
        self.gL_grB_0.addWidget(self.dEdit_0, 1, 1)

        # GrB for Cont subjects
        self.grB_1 = QtWidgets.QGroupBox(self.groupBox_sis_contracts)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grB_1.setFont(font)
        self.grB_1.setObjectName("grB_1")
        self.gL_grB_1 = QtWidgets.QGridLayout(self.grB_1)
        self.gL_grB_1.setObjectName("gL_grB_1")
        self.vL_groupBox_sis_contracts.addWidget(self.grB_1)

        self.lab_num_1 = QtWidgets.QLabel(self.grB_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_num_1.setFont(font)
        self.lab_num_1.setObjectName("lab_num_1")
        self.gL_grB_1.addWidget(self.lab_num_1, 0, 0)

        self.lEdit_1 = QtWidgets.QLineEdit(self.grB_1)
        self.lEdit_1.setObjectName("lEdit_1")
        self.gL_grB_1.addWidget(self.lEdit_1, 0, 1)

        self.lab_date_1 = QtWidgets.QLabel(self.grB_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_date_1.setFont(font)
        self.lab_date_1.setObjectName("lab_date_1")
        self.gL_grB_1.addWidget(self.lab_date_1, 1, 0)

        self.dEdit_1 = QtWidgets.QDateEdit(self.grB_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dEdit_1.setFont(font)
        self.dEdit_1.setDate(QtCore.QDate(2000, 1, 1))
        self.dEdit_1.setObjectName("dEdit_1")
        self.gL_grB_1.addWidget(self.dEdit_1, 1, 1)

        # GrB for Cont subjects
        self.grB_2 = QtWidgets.QGroupBox(self.groupBox_sis_contracts)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grB_2.setFont(font)
        self.grB_2.setObjectName("grB_2")
        self.gL_grB_2 = QtWidgets.QGridLayout(self.grB_2)
        self.gL_grB_2.setObjectName("gL_grB_2")
        self.vL_groupBox_sis_contracts.addWidget(self.grB_2)

        self.lab_num_2 = QtWidgets.QLabel(self.grB_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_num_2.setFont(font)
        self.lab_num_2.setObjectName("lab_num_2")
        self.gL_grB_2.addWidget(self.lab_num_2, 0, 0)

        self.lEdit_2 = QtWidgets.QLineEdit(self.grB_2)
        self.lEdit_2.setObjectName("lEdit_2")
        self.gL_grB_2.addWidget(self.lEdit_2, 0, 1)

        self.lab_date_2 = QtWidgets.QLabel(self.grB_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_date_2.setFont(font)
        self.lab_date_2.setObjectName("lab_date_2")
        self.gL_grB_2.addWidget(self.lab_date_2, 1, 0)

        self.dEdit_2 = QtWidgets.QDateEdit(self.grB_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dEdit_2.setFont(font)
        self.dEdit_2.setDate(QtCore.QDate(2000, 1, 1))
        self.dEdit_2.setObjectName("dEdit_2")
        self.gL_grB_2.addWidget(self.dEdit_2, 1, 1)

        # GrB for Cont subjects
        self.grB_3 = QtWidgets.QGroupBox(self.groupBox_sis_contracts)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grB_3.setFont(font)
        self.grB_3.setObjectName("grB_3")
        self.gL_grB_3 = QtWidgets.QGridLayout(self.grB_3)
        self.gL_grB_3.setObjectName("gL_grB_3")
        self.vL_groupBox_sis_contracts.addWidget(self.grB_3)

        self.lab_num_3 = QtWidgets.QLabel(self.grB_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_num_3.setFont(font)
        self.lab_num_3.setObjectName("lab_num_3")
        self.gL_grB_3.addWidget(self.lab_num_3, 0, 0)

        self.lEdit_3 = QtWidgets.QLineEdit(self.grB_3)
        self.lEdit_3.setObjectName("lEdit_3")
        self.gL_grB_3.addWidget(self.lEdit_3, 0, 1)

        self.lab_date_3 = QtWidgets.QLabel(self.grB_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_date_3.setFont(font)
        self.lab_date_3.setObjectName("lab_date_3")
        self.gL_grB_3.addWidget(self.lab_date_3, 1, 0)

        self.dEdit_3 = QtWidgets.QDateEdit(self.grB_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dEdit_3.setFont(font)
        self.dEdit_3.setDate(QtCore.QDate(2000, 1, 1))
        self.dEdit_3.setObjectName("dEdit_3")
        self.gL_grB_3.addWidget(self.dEdit_3, 1, 1)


        self.widget_enr_back_buts = QtWidgets.QWidget(self.widget_enr_input_box)
        self.widget_enr_back_buts.setObjectName("widget_enr_back_buts")
        self.hL_widget_enr_back_buts = QtWidgets.QHBoxLayout(self.widget_enr_back_buts)
        self.hL_widget_enr_back_buts.setObjectName("hL_widget_enr_back_buts")

        self.pushButton_enr_back = QtWidgets.QPushButton(self.widget_enr_back_buts)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_enr_back.setFont(font)
        self.pushButton_enr_back.setObjectName("pushButton_enr_back")
        self.hL_widget_enr_back_buts.addWidget(self.pushButton_enr_back)

        self.vL_widget_enr_input_box.addWidget(self.widget_enr_back_buts)

        self.hL_Enrollment.addWidget(self.widget_enr_input_box)
        self.widget_enr_list_box = QtWidgets.QWidget(Enrollment)
        self.widget_enr_list_box.setObjectName("widget_enr_list_box")
        self.vL_widget_enr_list_box = QtWidgets.QVBoxLayout(self.widget_enr_list_box)
        self.vL_widget_enr_list_box.setObjectName("vL_widget_enr_list_box")
        self.widget_left_up_enr = QtWidgets.QWidget(self.widget_enr_list_box)
        self.widget_left_up_enr.setObjectName("widget_left_up_enr")
        self.hL_widget_left_up_enr = QtWidgets.QHBoxLayout(self.widget_left_up_enr)
        self.hL_widget_left_up_enr.setObjectName("hL_widget_left_up_enr")
        self.label_search_enr = QtWidgets.QLabel(self.widget_left_up_enr)
        self.label_search_enr.setObjectName("label_search_enr")
        self.hL_widget_left_up_enr.addWidget(self.label_search_enr)
        self.lineEdit_search_enr = QtWidgets.QLineEdit(self.widget_left_up_enr)
        self.lineEdit_search_enr.setObjectName("lineEdit_search_enr")
        self.hL_widget_left_up_enr.addWidget(self.lineEdit_search_enr)
        self.vL_widget_enr_list_box.addWidget(self.widget_left_up_enr)
        self.scrollArea_enr_list = QtWidgets.QScrollArea(self.widget_enr_list_box)
        self.scrollArea_enr_list.setWidgetResizable(True)
        self.scrollArea_enr_list.setObjectName("scrollArea_enr_list")
        self.sAWContent_enr_list = QtWidgets.QWidget()
        self.sAWContent_enr_list.setGeometry(QtCore.QRect(0, 0, 559, 503))
        self.sAWContent_enr_list.setObjectName("sAWContent_enr_list")
        self.vL_sAWContent_enr_list = QtWidgets.QVBoxLayout(self.sAWContent_enr_list)
        self.vL_sAWContent_enr_list.setObjectName("vL_sAWContent_enr_list")
        self.scrollArea_enr_list.setWidget(self.sAWContent_enr_list)
        self.vL_widget_enr_list_box.addWidget(self.scrollArea_enr_list)
        self.hL_Enrollment.addWidget(self.widget_enr_list_box)
        self.hL_Enrollment.setStretch(0, 1)
        self.hL_Enrollment.setStretch(1, 2)

        self.list_cb_checked = []
        self.list_cb_check = []

        self.retranslateUi(Enrollment)
        QtCore.QMetaObject.connectSlotsByName(Enrollment)

    def retranslateUi(self, Enrollment):
        _translate = QtCore.QCoreApplication.translate
        Enrollment.setWindowTitle(_translate("Enrollment", "Зачисления"))
        self.pushButton_enr_save.setText(_translate("Enrollment", "Сохранить"))
        self.groupBox_stud_subs.setTitle(_translate("Enrollment", "Предметы"))
        self.groupBox_sis_contracts.setTitle(_translate("Enrollment", "Контракты"))
        self.grB_0.setTitle(_translate("Enrollment", "Физика"))
        self.grB_1.setTitle(_translate("Enrollment", "Математика"))
        self.grB_2.setTitle(_translate("Enrollment", "Математика"))
        self.grB_3.setTitle(_translate("Enrollment", "Математика"))
        self.el_CheckBox_sub_1.setText(_translate("Enrollment", "Информатика"))
        self.el_CheckBox_sub_2.setText(_translate("Enrollment", "Математика"))
        self.el_CheckBox_sub_3.setText(_translate("Enrollment", "Физика"))
        self.el_CheckBox_sub_4.setText(_translate("Enrollment", "Русский"))
        self.lab_date_0.setText(_translate("Enrollment", "Дата заключения контракта"))
        self.lab_date_1.setText(_translate("Enrollment", "Дата заключения контракта"))
        self.lab_date_2.setText(_translate("Enrollment", "Дата заключения контракта"))
        self.lab_date_3.setText(_translate("Enrollment", "Дата заключения контракта"))
        self.lab_num_0.setText(_translate("Enrollment", "Номер контракта"))
        self.lab_num_1.setText(_translate("Enrollment", "Номер контракта"))
        self.lab_num_2.setText(_translate("Enrollment", "Номер контракта"))
        self.lab_num_3.setText(_translate("Enrollment", "Номер контракта"))
        self.pushButton_enr_back.setText(_translate("Enrollment", "Назад"))
        self.label_search_enr.setText(_translate("Enrollment", "Поиск:"))
