from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enrollment(object):
    def setupUi(self, Enrollment):

        # Main settings
        Enrollment.setObjectName("Enrollment")
        Enrollment.resize(991, 588)
        self.hL_Enrollment = QtWidgets.QHBoxLayout(Enrollment)
        self.hL_Enrollment.setObjectName("hL_Enrollment")
        self.widget_enr_input_box = QtWidgets.QWidget(Enrollment)
        self.widget_enr_input_box.setObjectName("widget_enr_input_box")
        self.vL_widget_enr_input_box = QtWidgets.QVBoxLayout(self.widget_enr_input_box)
        self.vL_widget_enr_input_box.setObjectName("vL_widget_enr_input_box")
        self.widget_enr_edit_buts = QtWidgets.QWidget(self.widget_enr_input_box)
        self.widget_enr_edit_buts.setObjectName("widget_enr_edit_buts")
        self.hL_widget_enr_edit_buts = QtWidgets.QHBoxLayout(self.widget_enr_edit_buts)
        self.hL_widget_enr_edit_buts.setObjectName("hL_widget_enr_edit_buts")

        self.pushButton_enr_save = QtWidgets.QPushButton(self.widget_enr_edit_buts)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_enr_save.setFont(font)
        self.pushButton_enr_save.setObjectName("pushButton_enr_save")
        self.hL_widget_enr_edit_buts.addWidget(self.pushButton_enr_save)

        self.vL_widget_enr_input_box.addWidget(self.widget_enr_edit_buts)

        # Group Box for Subjects
        self.groupBox_stud_subs = QtWidgets.QGroupBox(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_stud_subs.setFont(font)
        self.groupBox_stud_subs.setObjectName("groupBox_stud_subs")
        self.hL_groupBox_stud_subs = QtWidgets.QHBoxLayout(self.groupBox_stud_subs)
        self.hL_groupBox_stud_subs.setObjectName("hL_groupBox_stud_subs")

        # CheckBoxes for gB
        self.el_CheckBox_sub_1 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_1.setFont(font)
        self.el_CheckBox_sub_1.setObjectName("el_CheckBox_sub_1")
        self.hL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_1)
        self.el_CheckBox_sub_2 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_2.setFont(font)
        self.el_CheckBox_sub_2.setObjectName("el_CheckBox_sub_2")
        self.hL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_2)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)
        self.el_CheckBox_sub_3 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_3.setFont(font)
        self.el_CheckBox_sub_3.setObjectName("el_CheckBox_sub_3")
        self.hL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_3)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)
        self.el_CheckBox_sub_4 = QtWidgets.QCheckBox(self.groupBox_stud_subs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.el_CheckBox_sub_4.setFont(font)
        self.el_CheckBox_sub_4.setObjectName("el_CheckBox_sub_4")
        self.hL_groupBox_stud_subs.addWidget(self.el_CheckBox_sub_4)
        self.vL_widget_enr_input_box.addWidget(self.groupBox_stud_subs)

        # Input and Label for numContract
        self.label_stud_contract = QtWidgets.QLabel(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_contract.setFont(font)
        self.label_stud_contract.setObjectName("label_stud_contract")
        self.vL_widget_enr_input_box.addWidget(self.label_stud_contract)
        self.lineEdit_stud_contract = QtWidgets.QLineEdit(self.widget_enr_input_box)
        self.lineEdit_stud_contract.setObjectName("lineEdit_stud_contract")
        self.vL_widget_enr_input_box.addWidget(self.lineEdit_stud_contract)

        self.label_stud_date_contract = QtWidgets.QLabel(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_date_contract.setFont(font)
        self.label_stud_date_contract.setObjectName("label_stud_date_contract")
        self.vL_widget_enr_input_box.addWidget(self.label_stud_date_contract)
        
        self.dateEdit_stud_contract = QtWidgets.QDateEdit(self.widget_enr_input_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_stud_contract.setFont(font)
        self.dateEdit_stud_contract.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit_stud_contract.setObjectName("dateEdit_stud_contract")
        self.vL_widget_enr_input_box.addWidget(self.dateEdit_stud_contract)

        self.widget_enr_back_buts = QtWidgets.QWidget(self.widget_enr_input_box)
        self.widget_enr_back_buts.setObjectName("widget_enr_back_buts")
        self.hL_widget_enr_back_buts = QtWidgets.QHBoxLayout(self.widget_enr_back_buts)
        self.hL_widget_enr_back_buts.setObjectName("hL_widget_enr_back_buts")

        self.pushButton_enr_back = QtWidgets.QPushButton(self.widget_enr_back_buts)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_enr_back.setFont(font)
        self.pushButton_enr_back.setObjectName("pushButton_enr_back")
        self.hL_widget_enr_back_buts.addWidget(self.pushButton_enr_back)

        self.vL_widget_enr_input_box.addWidget(self.widget_enr_back_buts)

        self.hL_Enrollment.addWidget(self.widget_enr_input_box)
        self.widget_enr_list_box = QtWidgets.QWidget(Enrollment)
        self.widget_enr_list_box.setObjectName("widget_enr_list_box")
        self.vL_widget_enr_list_box = QtWidgets.QVBoxLayout(self.widget_enr_list_box)
        self.vL_widget_enr_list_box.setObjectName("vL_widget_enr_list_box")
        self.widget_left_up_enr = QtWidgets.QWidget(self.widget_enr_list_box)
        self.widget_left_up_enr.setObjectName("widget_left_up_enr")
        self.hL_widget_left_up_enr = QtWidgets.QHBoxLayout(self.widget_left_up_enr)
        self.hL_widget_left_up_enr.setObjectName("hL_widget_left_up_enr")
        self.label_search_enr = QtWidgets.QLabel(self.widget_left_up_enr)
        self.label_search_enr.setObjectName("label_search_enr")
        self.hL_widget_left_up_enr.addWidget(self.label_search_enr)
        self.lineEdit_search_enr = QtWidgets.QLineEdit(self.widget_left_up_enr)
        self.lineEdit_search_enr.setObjectName("lineEdit_search_enr")
        self.hL_widget_left_up_enr.addWidget(self.lineEdit_search_enr)
        self.pushButton_enr_delete = QtWidgets.QPushButton(self.widget_left_up_enr)
        self.pushButton_enr_delete.setObjectName("pushButton_enr_delete")
        self.hL_widget_left_up_enr.addWidget(self.pushButton_enr_delete)
        self.vL_widget_enr_list_box.addWidget(self.widget_left_up_enr)
        self.scrollArea_enr_list = QtWidgets.QScrollArea(self.widget_enr_list_box)
        self.scrollArea_enr_list.setWidgetResizable(True)
        self.scrollArea_enr_list.setObjectName("scrollArea_enr_list")
        self.sAWContent_enr_list = QtWidgets.QWidget()
        self.sAWContent_enr_list.setGeometry(QtCore.QRect(0, 0, 559, 503))
        self.sAWContent_enr_list.setObjectName("sAWContent_enr_list")
        self.vL_sAWContent_enr_list = QtWidgets.QVBoxLayout(self.sAWContent_enr_list)
        self.vL_sAWContent_enr_list.setObjectName("vL_sAWContent_enr_list")
        self.scrollArea_enr_list.setWidget(self.sAWContent_enr_list)
        self.vL_widget_enr_list_box.addWidget(self.scrollArea_enr_list)
        self.hL_Enrollment.addWidget(self.widget_enr_list_box)
        self.hL_Enrollment.setStretch(0, 1)
        self.hL_Enrollment.setStretch(1, 2)

        self.retranslateUi(Enrollment)
        QtCore.QMetaObject.connectSlotsByName(Enrollment)

    def retranslateUi(self, Enrollment):
        _translate = QtCore.QCoreApplication.translate
        Enrollment.setWindowTitle(_translate("Enrollment", "Зачисления"))
        self.pushButton_enr_save.setText(_translate("Enrollment", "Сохранить"))
        self.groupBox_stud_subs.setTitle(_translate("Enrollment", "Предметы"))
        self.el_CheckBox_sub_1.setText(_translate("Enrollment", "Информатика"))
        self.el_CheckBox_sub_2.setText(_translate("Enrollment", "Математика"))
        self.el_CheckBox_sub_3.setText(_translate("Enrollment", "Физика"))
        self.el_CheckBox_sub_4.setText(_translate("Enrollment", "Русский"))
        self.label_stud_date_contract.setText(_translate("Enrollment", "Дата заключения контракта"))
        self.label_stud_contract.setText(_translate("Enrollment", "Номер контракта"))
        self.pushButton_enr_back.setText(_translate("Enrollment", "Назад"))
        self.label_search_enr.setText(_translate("Enrollment", "Поиск:"))
        self.pushButton_enr_delete.setText(_translate("Enrollment", "Удалить выбранную запись"))
