from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Students(object):
    def setupUi(self, Students):
        Students.setObjectName("Students")
        Students.resize(971, 678)
        self.hL_Students = QtWidgets.QHBoxLayout(Students)
        self.hL_Students.setObjectName("hL_Students")
        self.widget_stud_input_box = QtWidgets.QWidget(Students)
        self.widget_stud_input_box.setObjectName("widget_stud_input_box")
        self.vL_widget_stud_input_box = QtWidgets.QVBoxLayout(self.widget_stud_input_box)
        self.vL_widget_stud_input_box.setObjectName("vL_widget_stud_input_box")
        self.widget_stud_edit_buts = QtWidgets.QWidget(self.widget_stud_input_box)
        self.widget_stud_edit_buts.setObjectName("widget_stud_edit_buts")
        self.hL_widget_stud_edit_buts = QtWidgets.QHBoxLayout(self.widget_stud_edit_buts)
        self.hL_widget_stud_edit_buts.setObjectName("hL_widget_stud_edit_buts")
        self.pushButton_stud_add = QtWidgets.QPushButton(self.widget_stud_edit_buts)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_stud_add.setFont(font)
        self.pushButton_stud_add.setObjectName("pushButton_stud_add")
        self.hL_widget_stud_edit_buts.addWidget(self.pushButton_stud_add)
        self.pushButton_stud_save = QtWidgets.QPushButton(self.widget_stud_edit_buts)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_stud_save.setFont(font)
        self.pushButton_stud_save.setObjectName("pushButton_stud_save")
        self.hL_widget_stud_edit_buts.addWidget(self.pushButton_stud_save)
        self.vL_widget_stud_input_box.addWidget(self.widget_stud_edit_buts)
        self.label_stud_fullname = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_fullname.setFont(font)
        self.label_stud_fullname.setObjectName("label_stud_fullname")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_fullname)
        self.textEdit_stud_fullname = QtWidgets.QTextEdit(self.widget_stud_input_box)
        self.textEdit_stud_fullname.setObjectName("textEdit_stud_fullname")
        self.vL_widget_stud_input_box.addWidget(self.textEdit_stud_fullname)
        self.label_stud_group = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_group.setFont(font)
        self.label_stud_group.setObjectName("label_stud_group")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_group)
        self.comboBox_stud_group = QtWidgets.QComboBox(self.widget_stud_input_box)
        self.comboBox_stud_group.setObjectName("comboBox_stud_group")
        self.vL_widget_stud_input_box.addWidget(self.comboBox_stud_group)
        self.label_stud_birthday = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_birthday.setFont(font)
        self.label_stud_birthday.setObjectName("label_stud_birthday")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_birthday)
        self.dateEdit_stud_birthday = QtWidgets.QDateEdit(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_stud_birthday.setFont(font)
        self.dateEdit_stud_birthday.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit_stud_birthday.setObjectName("dateEdit_stud_birthday")
        self.vL_widget_stud_input_box.addWidget(self.dateEdit_stud_birthday)
        self.label_stud_phone = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_phone.setFont(font)
        self.label_stud_phone.setObjectName("label_stud_phone")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_phone)
        self.lineEdit_stud_phone = QtWidgets.QLineEdit(self.widget_stud_input_box)
        self.lineEdit_stud_phone.setObjectName("lineEdit_stud_phone")
        self.vL_widget_stud_input_box.addWidget(self.lineEdit_stud_phone)
        self.groupBox_stud_gender = QtWidgets.QGroupBox(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_stud_gender.setFont(font)
        self.groupBox_stud_gender.setObjectName("groupBox_stud_gender")
        self.hL_groupBox_stud_gender = QtWidgets.QHBoxLayout(self.groupBox_stud_gender)
        self.hL_groupBox_stud_gender.setObjectName("hL_groupBox_stud_gender")
        self.radioButton_stud_gender_male = QtWidgets.QRadioButton(self.groupBox_stud_gender)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_stud_gender_male.setFont(font)
        self.radioButton_stud_gender_male.setChecked(True)
        self.radioButton_stud_gender_male.setObjectName("radioButton_stud_gender_male")
        self.hL_groupBox_stud_gender.addWidget(self.radioButton_stud_gender_male)
        self.radioButton_stud_gender_female = QtWidgets.QRadioButton(self.groupBox_stud_gender)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_stud_gender_female.setFont(font)
        self.radioButton_stud_gender_female.setObjectName("radioButton_stud_gender_female")
        self.hL_groupBox_stud_gender.addWidget(self.radioButton_stud_gender_female)
        self.vL_widget_stud_input_box.addWidget(self.groupBox_stud_gender)
        self.label_stud_city = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_city.setFont(font)
        self.label_stud_city.setObjectName("label_stud_city")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_city)
        self.lineEdit_stud_city = QtWidgets.QLineEdit(self.widget_stud_input_box)
        self.lineEdit_stud_city.setObjectName("lineEdit_stud_city")
        self.vL_widget_stud_input_box.addWidget(self.lineEdit_stud_city)
        self.label_stud_einst = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_einst.setFont(font)
        self.label_stud_einst.setObjectName("label_stud_einst")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_einst)
        self.lineEdit_stud_einst = QtWidgets.QLineEdit(self.widget_stud_input_box)
        self.lineEdit_stud_einst.setObjectName("lineEdit_stud_einst")
        self.vL_widget_stud_input_box.addWidget(self.lineEdit_stud_einst)
        self.label_stud_mail = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_mail.setFont(font)
        self.label_stud_mail.setObjectName("label_stud_mail")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_mail)
        self.lineEdit_stud_mail = QtWidgets.QLineEdit(self.widget_stud_input_box)
        self.lineEdit_stud_mail.setObjectName("lineEdit_stud_mail")
        self.vL_widget_stud_input_box.addWidget(self.lineEdit_stud_mail)
        self.label_stud_web = QtWidgets.QLabel(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_stud_web.setFont(font)
        self.label_stud_web.setObjectName("label_stud_web")
        self.vL_widget_stud_input_box.addWidget(self.label_stud_web)
        self.lineEdit_stud_web = QtWidgets.QLineEdit(self.widget_stud_input_box)
        self.lineEdit_stud_web.setObjectName("lineEdit_stud_web")
        self.vL_widget_stud_input_box.addWidget(self.lineEdit_stud_web)
        self.pushButton_stud_back = QtWidgets.QPushButton(self.widget_stud_input_box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_stud_back.setFont(font)
        self.pushButton_stud_back.setObjectName("pushButton_stud_back")
        self.vL_widget_stud_input_box.addWidget(self.pushButton_stud_back)
        self.hL_Students.addWidget(self.widget_stud_input_box)
        self.widget_stud_list_box = QtWidgets.QWidget(Students)
        self.widget_stud_list_box.setObjectName("widget_stud_list_box")
        self.vL_widget_stud_list_box = QtWidgets.QVBoxLayout(self.widget_stud_list_box)
        self.vL_widget_stud_list_box.setObjectName("vL_widget_stud_list_box")
        self.widget_left_up_stud = QtWidgets.QWidget(self.widget_stud_list_box)
        self.widget_left_up_stud.setObjectName("widget_left_up_stud")
        self.hL_widget_left_up_stud = QtWidgets.QHBoxLayout(self.widget_left_up_stud)
        self.hL_widget_left_up_stud.setObjectName("hL_widget_left_up_stud")
        self.label_search_stud = QtWidgets.QLabel(self.widget_left_up_stud)
        self.label_search_stud.setObjectName("label_search_stud")
        self.hL_widget_left_up_stud.addWidget(self.label_search_stud)
        self.lineEdit_search_stud = QtWidgets.QLineEdit(self.widget_left_up_stud)
        self.lineEdit_search_stud.setObjectName("lineEdit_search_stud")
        self.hL_widget_left_up_stud.addWidget(self.lineEdit_search_stud)
        self.pushButton_stud_delete = QtWidgets.QPushButton(self.widget_left_up_stud)
        self.pushButton_stud_delete.setObjectName("pushButton_stud_delete")
        self.hL_widget_left_up_stud.addWidget(self.pushButton_stud_delete)
        self.vL_widget_stud_list_box.addWidget(self.widget_left_up_stud)
        self.scrollArea_stud_list = QtWidgets.QScrollArea(self.widget_stud_list_box)
        self.scrollArea_stud_list.setWidgetResizable(True)
        self.scrollArea_stud_list.setObjectName("scrollArea_stud_list")
        self.sAWContent_stud_list = QtWidgets.QWidget()
        self.sAWContent_stud_list.setGeometry(QtCore.QRect(0, 0, 539, 593))
        self.sAWContent_stud_list.setObjectName("sAWContent_stud_list")
        self.vL_sAWContent_stud_list = QtWidgets.QVBoxLayout(self.sAWContent_stud_list)
        self.vL_sAWContent_stud_list.setObjectName("vL_sAWContent_stud_list")
        self.scrollArea_stud_list.setWidget(self.sAWContent_stud_list)
        self.vL_widget_stud_list_box.addWidget(self.scrollArea_stud_list)
        self.hL_Students.addWidget(self.widget_stud_list_box)
        self.hL_Students.setStretch(0, 1)
        self.hL_Students.setStretch(1, 2)

        self.retranslateUi(Students)
        QtCore.QMetaObject.connectSlotsByName(Students)

    def retranslateUi(self, Students):
        _translate = QtCore.QCoreApplication.translate
        Students.setWindowTitle(_translate("Students", "Обучающиеся"))
        self.pushButton_stud_add.setText(_translate("Students", "Добавить новую запись"))
        self.pushButton_stud_save.setText(_translate("Students", "Сохранить в выбранную запись"))
        self.label_stud_fullname.setText(_translate("Students", "ФИО обучающегося"))
        self.label_stud_group.setText(_translate("Students", "Группа"))
        self.label_stud_birthday.setText(_translate("Students", "День рождения"))
        self.label_stud_phone.setText(_translate("Students", "Телефон (не обязательно)"))
        self.groupBox_stud_gender.setTitle(_translate("Students", "Пол"))
        self.radioButton_stud_gender_male.setText(_translate("Students", "Мужской"))
        self.radioButton_stud_gender_female.setText(_translate("Students", "Женский"))
        self.label_stud_city.setText(_translate("Students", "Место проживания (не обязательно)"))
        self.label_stud_einst.setText(_translate("Students", "Место обучения (не обязательно)"))
        self.label_stud_mail.setText(_translate("Students", "Электронная почта (не обязательно)"))
        self.label_stud_web.setText(_translate("Students", "Социальные сети (не обязательно)"))
        self.pushButton_stud_back.setText(_translate("Students", "Назад"))
        self.label_search_stud.setText(_translate("Students", "Поиск:"))
        self.pushButton_stud_delete.setText(_translate("Students", "Удалить выбранную запись"))
