from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Jobs in Main
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 556)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Projects\\ARM_s_CPUI\\interface\\../sfu_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.mainwidget = QtWidgets.QWidget(MainWindow)
        self.mainwidget.setObjectName("mainwidget")
        self.hL_mainwidget = QtWidgets.QHBoxLayout(self.mainwidget)
        self.hL_mainwidget.setObjectName("hL_mainwidget")
        self.widget_Main = QtWidgets.QWidget(self.mainwidget)
        self.widget_Main.setObjectName("widget_Main")
        self.vL_widget_Main = QtWidgets.QVBoxLayout(self.widget_Main)
        self.vL_widget_Main.setObjectName("vL_widget_Main")
        self.tabWidget_Main = QtWidgets.QTabWidget(self.widget_Main)
        self.tabWidget_Main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Main.sizePolicy().hasHeightForWidth())
        self.tabWidget_Main.setSizePolicy(sizePolicy)
        self.tabWidget_Main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_Main.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_Main.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_Main.setDocumentMode(True)
        self.tabWidget_Main.setTabsClosable(False)
        self.tabWidget_Main.setMovable(False)
        self.tabWidget_Main.setTabBarAutoHide(False)
        self.tabWidget_Main.setObjectName("tabWidget_Main")

        # TAB ROSTER
        self.tab_roster = QtWidgets.QWidget()
        self.tab_roster.setObjectName("tab_roster")
        self.vL_tab_roster = QtWidgets.QVBoxLayout(self.tab_roster)
        self.vL_tab_roster.setObjectName("vL_tab_roster")
        self.widget_roster_editors = QtWidgets.QWidget(self.tab_roster)
        self.widget_roster_editors.setObjectName("widget_roster_editors")
        self.hL_widget_roster_editors = QtWidgets.QHBoxLayout(self.widget_roster_editors)
        self.hL_widget_roster_editors.setObjectName("hL_widget_roster_editors")
        self.widget_roster = QtWidgets.QWidget(self.widget_roster_editors)
        self.widget_roster.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.widget_roster.setFont(font)
        self.widget_roster.setObjectName("widget_roster")
        self.gL_roster = QtWidgets.QGridLayout(self.widget_roster)
        self.gL_roster.setObjectName("gL_roster")
        self.pushButton_headers_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_headers_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_headers_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_headers_roster.setFont(font)
        self.pushButton_headers_roster.setObjectName("pushButton_headers_roster")
        self.gL_roster.addWidget(self.pushButton_headers_roster, 2, 2, 1, 1)
        self.pushButton_students_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_students_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_students_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_students_roster.setFont(font)
        self.pushButton_students_roster.setObjectName("pushButton_students_roster")
        self.gL_roster.addWidget(self.pushButton_students_roster, 1, 1, 1, 1)
        self.pushButton_subjects_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_subjects_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_subjects_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_subjects_roster.setFont(font)
        self.pushButton_subjects_roster.setObjectName("pushButton_subjects_roster")
        self.gL_roster.addWidget(self.pushButton_subjects_roster, 2, 1, 1, 1)
        self.pushButton_programs_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_programs_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_programs_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_programs_roster.setFont(font)
        self.pushButton_programs_roster.setObjectName("pushButton_programs_roster")
        self.gL_roster.addWidget(self.pushButton_programs_roster, 1, 2, 1, 1)
        self.pushButton_teachers_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_teachers_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_teachers_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_teachers_roster.setFont(font)
        self.pushButton_teachers_roster.setObjectName("pushButton_teachers_roster")
        self.gL_roster.addWidget(self.pushButton_teachers_roster, 0, 2, 1, 1)
        self.pushButton_groups_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_groups_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_groups_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_groups_roster.setFont(font)
        self.pushButton_groups_roster.setObjectName("pushButton_groups_roster")
        self.gL_roster.addWidget(self.pushButton_groups_roster, 0, 1, 1, 1)
        self.pushButton_enrollment_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enrollment_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_enrollment_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_enrollment_roster.setFont(font)
        self.pushButton_enrollment_roster.setObjectName("pushButton_enrollment_roster")
        self.gL_roster.addWidget(self.pushButton_enrollment_roster, 3, 2, 1, 1)
        self.hL_widget_roster_editors.addWidget(self.widget_roster)
        self.vL_tab_roster.addWidget(self.widget_roster_editors)
        self.tabWidget_Main.addTab(self.tab_roster, "")

        # TAB TIMETABLE or TTABLE
        self.tab_timetable = QtWidgets.QWidget()
        self.tab_timetable.setEnabled(True)
        self.tab_timetable.setObjectName("tab_timetable")
        self.vL_tab_timetable = QtWidgets.QVBoxLayout(self.tab_timetable)
        self.vL_tab_timetable.setObjectName("vL_tab_timetable")
        self.widget_timetable = QtWidgets.QWidget(self.tab_timetable)
        self.widget_timetable.setObjectName("widget_timetable")
        self.vL_widget_timetable = QtWidgets.QVBoxLayout(self.widget_timetable)
        self.vL_widget_timetable.setObjectName("vL_widget_timetable")
        self.widget_Up_timetable = QtWidgets.QWidget(self.widget_timetable)
        self.widget_Up_timetable.setObjectName("widget_Up_timetable")
        self.hL_widget_Up_timetable = QtWidgets.QHBoxLayout(self.widget_Up_timetable)
        self.hL_widget_Up_timetable.setObjectName("hL_widget_Up_timetable")
        self.pushButton_edit_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_edit_timetable.sizePolicy().hasHeightForWidth())
        self.pushButton_edit_timetable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_edit_timetable.setFont(font)
        self.pushButton_edit_timetable.setToolTipDuration(-1)
        self.pushButton_edit_timetable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_edit_timetable.setAutoDefault(False)
        self.pushButton_edit_timetable.setDefault(False)
        self.pushButton_edit_timetable.setFlat(False)
        self.pushButton_edit_timetable.setObjectName("pushButton_edit_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_edit_timetable)

        self.pushButton_update_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_update_timetable.setFont(font)
        self.pushButton_update_timetable.setObjectName("pushButton_update_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_update_timetable)

        self.pushButton_print_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_print_timetable.setFont(font)
        self.pushButton_print_timetable.setObjectName("pushButton_print_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_print_timetable)

        self.label_search_timetable = QtWidgets.QLabel(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_search_timetable.sizePolicy().hasHeightForWidth())
        self.label_search_timetable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_search_timetable.setFont(font)
        self.label_search_timetable.setObjectName("label_search_timetable")
        self.hL_widget_Up_timetable.addWidget(self.label_search_timetable)
        self.lineEdit_search_timetable = QtWidgets.QLineEdit(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search_timetable.sizePolicy().hasHeightForWidth())
        self.lineEdit_search_timetable.setSizePolicy(sizePolicy)
        self.lineEdit_search_timetable.setObjectName("lineEdit_search_timetable")
        self.hL_widget_Up_timetable.addWidget(self.lineEdit_search_timetable)
        self.vL_widget_timetable.addWidget(self.widget_Up_timetable)
        self.scrollArea_timetable = QtWidgets.QScrollArea(self.widget_timetable)
        self.scrollArea_timetable.setWidgetResizable(True)
        self.scrollArea_timetable.setObjectName("scrollArea_timetable")
        self.sAWContent_timetable = QtWidgets.QWidget()
        self.sAWContent_timetable.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_timetable.setObjectName("sAWContent_timetable")
        self.vL_sAWContent_timetable = QtWidgets.QVBoxLayout(self.sAWContent_timetable)
        self.vL_sAWContent_timetable.setObjectName("vL_sAWContent_timetable")
        self.scrollArea_timetable.setWidget(self.sAWContent_timetable)
        self.vL_widget_timetable.addWidget(self.scrollArea_timetable)
        self.vL_tab_timetable.addWidget(self.widget_timetable)
        self.tabWidget_Main.addTab(self.tab_timetable, "")

        # TAB DECREE
        self.tab_decree = QtWidgets.QWidget()
        self.tab_decree.setObjectName("tab_decree")
        self.vL_tab_decree = QtWidgets.QVBoxLayout(self.tab_decree)
        self.vL_tab_decree.setObjectName("vL_tab_decree")
        self.widget_decree = QtWidgets.QWidget(self.tab_decree)
        self.widget_decree.setObjectName("widget_decree")
        self.vL_widget_decree = QtWidgets.QVBoxLayout(self.widget_decree)
        self.vL_widget_decree.setObjectName("vL_widget_decree")
        self.widget_up_decree = QtWidgets.QWidget(self.widget_decree)
        self.widget_up_decree.setObjectName("widget_up_decree")
        self.hL_widget_up_decree = QtWidgets.QHBoxLayout(self.widget_up_decree)
        self.hL_widget_up_decree.setObjectName("hL_widget_up_decree")
        self.pushButton_create_decree = QtWidgets.QPushButton(self.widget_up_decree)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_create_decree.setFont(font)
        self.pushButton_create_decree.setObjectName("pushButton_create_decree")
        self.hL_widget_up_decree.addWidget(self.pushButton_create_decree)
        self.pushButton_edit_decree = QtWidgets.QPushButton(self.widget_up_decree)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_edit_decree.setFont(font)
        self.pushButton_edit_decree.setObjectName("pushButton_edit_decree")
        self.hL_widget_up_decree.addWidget(self.pushButton_edit_decree)
        self.pushButton_print_decree = QtWidgets.QPushButton(self.widget_up_decree)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_print_decree.setFont(font)
        self.pushButton_print_decree.setObjectName("pushButton_print_decree")
        self.hL_widget_up_decree.addWidget(self.pushButton_print_decree)
        self.label_search_decree = QtWidgets.QLabel(self.widget_up_decree)
        self.label_search_decree.setObjectName("label_search_decree")
        self.hL_widget_up_decree.addWidget(self.label_search_decree)
        self.lineEdit_search_decree = QtWidgets.QLineEdit(self.widget_up_decree)
        self.lineEdit_search_decree.setObjectName("lineEdit_search_decree")
        self.hL_widget_up_decree.addWidget(self.lineEdit_search_decree)
        self.vL_widget_decree.addWidget(self.widget_up_decree)
        self.scrollArea_decree = QtWidgets.QScrollArea(self.widget_decree)
        self.scrollArea_decree.setWidgetResizable(True)
        self.scrollArea_decree.setObjectName("scrollArea_decree")
        self.sAWContent_decree = QtWidgets.QWidget()
        self.sAWContent_decree.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_decree.setObjectName("sAWContent_decree")
        self.vL_sAWContent_decree = QtWidgets.QVBoxLayout(self.sAWContent_decree)
        self.vL_sAWContent_decree.setObjectName("vL_sAWContent_decree")
        self.scrollArea_decree.setWidget(self.sAWContent_decree)
        self.vL_widget_decree.addWidget(self.scrollArea_decree)
        self.vL_tab_decree.addWidget(self.widget_decree)
        self.tabWidget_Main.addTab(self.tab_decree, "")

        # TAB NOTES
        self.tab_notes = QtWidgets.QWidget()
        self.tab_notes.setObjectName("tab_notes")
        self.vL_tab_notes = QtWidgets.QVBoxLayout(self.tab_notes)
        self.vL_tab_notes.setObjectName("vL_tab_notes")
        self.widget_notes = QtWidgets.QWidget(self.tab_notes)
        self.widget_notes.setObjectName("widget_notes")
        self.vL_widget_notes = QtWidgets.QVBoxLayout(self.widget_notes)
        self.vL_widget_notes.setObjectName("vL_widget_notes")
        self.widget_up_notes = QtWidgets.QWidget(self.widget_notes)
        self.widget_up_notes.setObjectName("widget_up_notes")
        self.hL_widget_up_notes = QtWidgets.QHBoxLayout(self.widget_up_notes)
        self.hL_widget_up_notes.setObjectName("hL_widget_up_notes")
        self.pushButton_create_notes = QtWidgets.QPushButton(self.widget_up_notes)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_create_notes.setFont(font)
        self.pushButton_create_notes.setObjectName("pushButton_create_notes")
        self.hL_widget_up_notes.addWidget(self.pushButton_create_notes)
        self.pushButton_edit_notes = QtWidgets.QPushButton(self.widget_up_notes)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_edit_notes.setFont(font)
        self.pushButton_edit_notes.setObjectName("pushButton_edit_notes")
        self.hL_widget_up_notes.addWidget(self.pushButton_edit_notes)
        self.pushButton_print_notes = QtWidgets.QPushButton(self.widget_up_notes)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_print_notes.setFont(font)
        self.pushButton_print_notes.setObjectName("pushButton_print_notes")
        self.hL_widget_up_notes.addWidget(self.pushButton_print_notes)
        self.label_search_notes = QtWidgets.QLabel(self.widget_up_notes)
        self.label_search_notes.setObjectName("label_search_notes")
        self.hL_widget_up_notes.addWidget(self.label_search_notes)
        self.lineEdit_search_notes = QtWidgets.QLineEdit(self.widget_up_notes)
        self.lineEdit_search_notes.setObjectName("lineEdit_search_notes")
        self.hL_widget_up_notes.addWidget(self.lineEdit_search_notes)
        self.vL_widget_notes.addWidget(self.widget_up_notes)
        self.scrollArea_notes = QtWidgets.QScrollArea(self.widget_notes)
        self.scrollArea_notes.setWidgetResizable(True)
        self.scrollArea_notes.setObjectName("scrollArea_notes")
        self.sAWContent_notes = QtWidgets.QWidget()
        self.sAWContent_notes.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_notes.setObjectName("sAWContent_notes")
        self.vL_sAWContent_notes = QtWidgets.QVBoxLayout(self.sAWContent_notes)
        self.vL_sAWContent_notes.setObjectName("vL_sAWContent_notes")
        self.scrollArea_notes.setWidget(self.sAWContent_notes)
        self.vL_widget_notes.addWidget(self.scrollArea_notes)
        self.vL_tab_notes.addWidget(self.widget_notes)
        self.tabWidget_Main.addTab(self.tab_notes, "")

        # Main actions menu and other
        self.vL_widget_Main.addWidget(self.tabWidget_Main)
        self.hL_mainwidget.addWidget(self.widget_Main)
        MainWindow.setCentralWidget(self.mainwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АРМ специалиста ЦПЮИ"))
        self.pushButton_headers_roster.setText(_translate("MainWindow", "Должностные лица"))
        self.pushButton_students_roster.setText(_translate("MainWindow", "Обучающиеся"))
        self.pushButton_subjects_roster.setText(_translate("MainWindow", "Предметы"))
        self.pushButton_programs_roster.setText(_translate("MainWindow", "Образовательные программы"))
        self.pushButton_teachers_roster.setText(_translate("MainWindow", "Преподаватели"))
        self.pushButton_groups_roster.setText(_translate("MainWindow", "Группы"))
        self.pushButton_enrollment_roster.setText(_translate("MainWindow", "Зачисления"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_roster), _translate("MainWindow", "Реестр"))
        self.pushButton_edit_timetable.setText(_translate("MainWindow", "Изменить расписание"))
        self.pushButton_print_timetable.setText(_translate("MainWindow", "Печать"))
        self.pushButton_update_timetable.setText(_translate("MainWindow", "Обновить список"))
        self.label_search_timetable.setText(_translate("MainWindow", "Поиск:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_timetable), _translate("MainWindow", "Расписание"))
        self.pushButton_create_decree.setText(_translate("MainWindow", "Создать новый приказ"))
        self.pushButton_edit_decree.setText(_translate("MainWindow", "Редактировать выбранный приказ"))
        self.pushButton_print_decree.setText(_translate("MainWindow", "Печать"))
        self.label_search_decree.setText(_translate("MainWindow", "Поиск:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_decree), _translate("MainWindow", "Приказы"))
        self.pushButton_create_notes.setText(_translate("MainWindow", "Создать новую записку"))
        self.pushButton_edit_notes.setText(_translate("MainWindow", "Редактировать выбранную записку"))
        self.pushButton_print_notes.setText(_translate("MainWindow", "Печать"))
        self.label_search_notes.setText(_translate("MainWindow", "Поиск:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_notes), _translate("MainWindow", "Служебные записки"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
