from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Jobs in Main
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 885)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Projects\\ARM_s_CPUI\\interface\\../sfu_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.mainwidget = QtWidgets.QWidget(MainWindow)
        self.mainwidget.setObjectName("mainwidget")
        self.hL_mainwidget = QtWidgets.QHBoxLayout(self.mainwidget)
        self.hL_mainwidget.setObjectName("hL_mainwidget")
        self.widget_Main = QtWidgets.QWidget(self.mainwidget)
        self.widget_Main.setObjectName("widget_Main")
        self.vL_widget_Main = QtWidgets.QVBoxLayout(self.widget_Main)
        self.vL_widget_Main.setObjectName("vL_widget_Main")
        self.tabWidget_Main = QtWidgets.QTabWidget(self.widget_Main)
        self.tabWidget_Main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Main.sizePolicy().hasHeightForWidth())
        self.tabWidget_Main.setSizePolicy(sizePolicy)
        self.tabWidget_Main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_Main.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_Main.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_Main.setDocumentMode(True)
        self.tabWidget_Main.setTabsClosable(False)
        self.tabWidget_Main.setMovable(False)
        self.tabWidget_Main.setTabBarAutoHide(False)
        self.tabWidget_Main.setObjectName("tabWidget_Main")

        # TAB ROSTER
        self.tab_roster = QtWidgets.QWidget()
        self.tab_roster.setObjectName("tab_roster")
        self.vL_tab_roster = QtWidgets.QVBoxLayout(self.tab_roster)
        self.vL_tab_roster.setObjectName("vL_tab_roster")
        self.widget_roster_editors = QtWidgets.QWidget(self.tab_roster)
        self.widget_roster_editors.setObjectName("widget_roster_editors")
        self.hL_widget_roster_editors = QtWidgets.QHBoxLayout(self.widget_roster_editors)
        self.hL_widget_roster_editors.setObjectName("hL_widget_roster_editors")
        self.widget_roster = QtWidgets.QWidget(self.widget_roster_editors)
        self.widget_roster.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.widget_roster.setFont(font)
        self.widget_roster.setObjectName("widget_roster")
        self.gL_roster = QtWidgets.QGridLayout(self.widget_roster)
        self.gL_roster.setObjectName("gL_roster")

        self.pushButton_headers_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_headers_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_headers_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_headers_roster.setFont(font)
        self.pushButton_headers_roster.setObjectName("pushButton_headers_roster")
        self.gL_roster.addWidget(self.pushButton_headers_roster, 2, 2, 1, 1)

        self.pushButton_students_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_students_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_students_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_students_roster.setFont(font)
        self.pushButton_students_roster.setObjectName("pushButton_students_roster")
        self.gL_roster.addWidget(self.pushButton_students_roster, 1, 1, 1, 1)

        self.pushButton_subjects_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_subjects_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_subjects_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_subjects_roster.setFont(font)
        self.pushButton_subjects_roster.setObjectName("pushButton_subjects_roster")
        self.gL_roster.addWidget(self.pushButton_subjects_roster, 2, 1, 1, 1)

        self.pushButton_programs_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_programs_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_programs_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_programs_roster.setFont(font)
        self.pushButton_programs_roster.setObjectName("pushButton_programs_roster")
        self.gL_roster.addWidget(self.pushButton_programs_roster, 1, 2, 1, 1)

        self.pushButton_teachers_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_teachers_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_teachers_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_teachers_roster.setFont(font)
        self.pushButton_teachers_roster.setObjectName("pushButton_teachers_roster")
        self.gL_roster.addWidget(self.pushButton_teachers_roster, 0, 2, 1, 1)
        self.pushButton_groups_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_groups_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_groups_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_groups_roster.setFont(font)
        self.pushButton_groups_roster.setObjectName("pushButton_groups_roster")
        self.gL_roster.addWidget(self.pushButton_groups_roster, 0, 1, 1, 1)

        self.pushButton_enrollment_roster = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enrollment_roster.sizePolicy().hasHeightForWidth())
        self.pushButton_enrollment_roster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_enrollment_roster.setFont(font)
        self.pushButton_enrollment_roster.setObjectName("pushButton_enrollment_roster")
        self.gL_roster.addWidget(self.pushButton_enrollment_roster, 3, 2, 1, 1)

        self.pushButton_outlay = QtWidgets.QPushButton(self.widget_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_outlay.sizePolicy().hasHeightForWidth())
        self.pushButton_outlay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushButton_outlay.setFont(font)
        self.pushButton_outlay.setObjectName("pushButton_outlay")
        self.gL_roster.addWidget(self.pushButton_outlay, 3, 1, 1, 1)

        self.hL_widget_roster_editors.addWidget(self.widget_roster)
        self.vL_tab_roster.addWidget(self.widget_roster_editors)
        self.tabWidget_Main.addTab(self.tab_roster, "")

        # TAB TIMETABLE or TTABLE
        self.tab_timetable = QtWidgets.QWidget()
        self.tab_timetable.setEnabled(True)
        self.tab_timetable.setObjectName("tab_timetable")
        self.vL_tab_timetable = QtWidgets.QVBoxLayout(self.tab_timetable)
        self.vL_tab_timetable.setObjectName("vL_tab_timetable")
        self.widget_timetable = QtWidgets.QWidget(self.tab_timetable)
        self.widget_timetable.setObjectName("widget_timetable")
        self.vL_widget_timetable = QtWidgets.QVBoxLayout(self.widget_timetable)
        self.vL_widget_timetable.setObjectName("vL_widget_timetable")
        self.widget_Up_timetable = QtWidgets.QWidget(self.widget_timetable)
        self.widget_Up_timetable.setObjectName("widget_Up_timetable")
        self.hL_widget_Up_timetable = QtWidgets.QHBoxLayout(self.widget_Up_timetable)
        self.hL_widget_Up_timetable.setObjectName("hL_widget_Up_timetable")
        self.pushButton_edit_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_edit_timetable.sizePolicy().hasHeightForWidth())
        self.pushButton_edit_timetable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_edit_timetable.setFont(font)
        self.pushButton_edit_timetable.setToolTipDuration(-1)
        self.pushButton_edit_timetable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_edit_timetable.setAutoDefault(False)
        self.pushButton_edit_timetable.setDefault(False)
        self.pushButton_edit_timetable.setFlat(False)
        self.pushButton_edit_timetable.setObjectName("pushButton_edit_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_edit_timetable)

        self.pushButton_update_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_update_timetable.setFont(font)
        self.pushButton_update_timetable.setObjectName("pushButton_update_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_update_timetable)

        self.pushButton_print_timetable = QtWidgets.QPushButton(self.widget_Up_timetable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_print_timetable.setFont(font)
        self.pushButton_print_timetable.setObjectName("pushButton_print_timetable")
        self.hL_widget_Up_timetable.addWidget(self.pushButton_print_timetable)

        self.label_search_timetable = QtWidgets.QLabel(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_search_timetable.sizePolicy().hasHeightForWidth())
        self.label_search_timetable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_search_timetable.setFont(font)
        self.label_search_timetable.setObjectName("label_search_timetable")
        self.hL_widget_Up_timetable.addWidget(self.label_search_timetable)
        self.lineEdit_search_timetable = QtWidgets.QLineEdit(self.widget_Up_timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search_timetable.sizePolicy().hasHeightForWidth())
        self.lineEdit_search_timetable.setSizePolicy(sizePolicy)
        self.lineEdit_search_timetable.setObjectName("lineEdit_search_timetable")
        self.hL_widget_Up_timetable.addWidget(self.lineEdit_search_timetable)
        self.vL_widget_timetable.addWidget(self.widget_Up_timetable)
        self.scrollArea_timetable = QtWidgets.QScrollArea(self.widget_timetable)
        self.scrollArea_timetable.setWidgetResizable(True)
        self.scrollArea_timetable.setObjectName("scrollArea_timetable")
        self.sAWContent_timetable = QtWidgets.QWidget()
        self.sAWContent_timetable.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_timetable.setObjectName("sAWContent_timetable")
        self.vL_sAWContent_timetable = QtWidgets.QVBoxLayout(self.sAWContent_timetable)
        self.vL_sAWContent_timetable.setObjectName("vL_sAWContent_timetable")
        self.scrollArea_timetable.setWidget(self.sAWContent_timetable)
        self.vL_widget_timetable.addWidget(self.scrollArea_timetable)
        self.vL_tab_timetable.addWidget(self.widget_timetable)
        self.tabWidget_Main.addTab(self.tab_timetable, "")

        # TAB DOCX
        self.tab_docx = QtWidgets.QWidget()
        self.tab_docx.setObjectName("tab_docx")
        self.tabWidget_Main.addTab(self.tab_docx, "")
        self.vL_tab_docx = QtWidgets.QVBoxLayout(self.tab_docx)
        self.vL_tab_docx.setObjectName("vL_tab_docx")
        self.widget_docx = QtWidgets.QWidget(self.tab_docx)
        self.widget_docx.setObjectName("widget_docx")
        self.vL_tab_docx.addWidget(self.widget_docx)

        self.vL_widget_docx = QtWidgets.QVBoxLayout(self.widget_docx)
        self.vL_widget_docx.setObjectName("vL_widget_docx")
        self.widget_up_docx = QtWidgets.QWidget(self.widget_docx)
        self.widget_up_docx.setObjectName("widget_up_docx")
        self.vL_widget_docx.addWidget(self.widget_up_docx)

        self.gL_widget_up_docx = QtWidgets.QGridLayout(self.widget_up_docx)
        self.gL_widget_up_docx.setObjectName("hL_widget_up_docx")

        self.pushButton_create_docx = QtWidgets.QPushButton(self.widget_up_docx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_create_docx.setFont(font)
        self.pushButton_create_docx.setObjectName("pushButton_create_docx")
        self.gL_widget_up_docx.addWidget(self.pushButton_create_docx, 0, 0)

        self.pushButton_edit_docx = QtWidgets.QPushButton(self.widget_up_docx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_edit_docx.setFont(font)
        self.pushButton_edit_docx.setObjectName("pushButton_edit_docx")
        self.gL_widget_up_docx.addWidget(self.pushButton_edit_docx, 0, 1)

        self.pushButton_del_docx = QtWidgets.QPushButton(self.widget_up_docx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_del_docx.setFont(font)
        self.pushButton_del_docx.setObjectName("pushButton_del_docx")
        self.gL_widget_up_docx.addWidget(self.pushButton_del_docx, 0, 3)

        self.pushButton_print_docx = QtWidgets.QPushButton(self.widget_up_docx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_print_docx.setFont(font)
        self.pushButton_print_docx.setObjectName("pushButton_print_docx")
        self.gL_widget_up_docx.addWidget(self.pushButton_print_docx, 0, 2)

        self.pushButton_update_docx = QtWidgets.QPushButton(self.widget_up_docx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_update_docx.setFont(font)
        self.pushButton_update_docx.setObjectName("pushButton_update_docx")
        self.gL_widget_up_docx.addWidget(self.pushButton_update_docx, 1, 0)

        self.label_search_docx = QtWidgets.QLabel(self.widget_up_docx)
        self.label_search_docx.setObjectName("label_search_docx")
        self.gL_widget_up_docx.addWidget(self.label_search_docx, 1, 1)

        self.lineEdit_search_docx = QtWidgets.QLineEdit(self.widget_up_docx)
        self.lineEdit_search_docx.setObjectName("lineEdit_search_docx")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search_docx.sizePolicy().hasHeightForWidth())
        self.lineEdit_search_docx.setSizePolicy(sizePolicy)
        self.gL_widget_up_docx.addWidget(self.lineEdit_search_docx, 1, 2, 1, 2)

        self.tabWidget_docx = QtWidgets.QTabWidget(self.widget_docx)
        self.tabWidget_docx.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_docx.sizePolicy().hasHeightForWidth())
        self.tabWidget_docx.setSizePolicy(sizePolicy)
        self.tabWidget_docx.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_docx.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_docx.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_docx.setDocumentMode(True)
        self.tabWidget_docx.setTabsClosable(False)
        self.tabWidget_docx.setMovable(False)
        self.tabWidget_docx.setTabBarAutoHide(False)
        self.tabWidget_docx.setObjectName("tabWidget_docx")
        self.vL_widget_docx.addWidget(self.tabWidget_docx)

        # TAB DECREE
        self.tab_decree = QtWidgets.QWidget(self.tabWidget_docx)
        self.tab_decree.setObjectName("tab_decree")
        self.vL_tab_decree = QtWidgets.QVBoxLayout(self.tab_decree)
        self.vL_tab_decree.setObjectName("vL_tab_decree")
        self.tabWidget_docx.addTab(self.tab_decree, "")

        self.scrollArea_decree = QtWidgets.QScrollArea(self.widget_docx)
        self.scrollArea_decree.setWidgetResizable(True)
        self.scrollArea_decree.setObjectName("scrollArea_decree")
        self.sAWContent_decree = QtWidgets.QWidget(self.tab_decree)
        self.sAWContent_decree.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_decree.setObjectName("sAWContent_decree")
        self.vL_sAWContent_decree = QtWidgets.QVBoxLayout(self.sAWContent_decree)
        self.vL_sAWContent_decree.setObjectName("vL_sAWContent_decree")
        self.scrollArea_decree.setWidget(self.sAWContent_decree)
        self.vL_tab_decree.addWidget(self.scrollArea_decree)

        # TAB NOTES
        self.tab_notes = QtWidgets.QWidget(self.tabWidget_docx)
        self.tab_notes.setObjectName("tab_notes")
        self.vL_tab_notes = QtWidgets.QVBoxLayout(self.tab_notes)
        self.vL_tab_notes.setObjectName("vL_tab_notes")
        self.tabWidget_docx.addTab(self.tab_notes, "")

        self.scrollArea_notes = QtWidgets.QScrollArea(self.widget_docx)
        self.scrollArea_notes.setWidgetResizable(True)
        self.scrollArea_notes.setObjectName("scrollArea_notes")
        self.sAWContent_notes = QtWidgets.QWidget(self.tab_notes)
        self.sAWContent_notes.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_notes.setObjectName("sAWContent_notes")
        self.vL_sAWContent_notes = QtWidgets.QVBoxLayout(self.sAWContent_notes)
        self.vL_sAWContent_notes.setObjectName("vL_sAWContent_notes")
        self.scrollArea_notes.setWidget(self.sAWContent_notes)
        self.vL_tab_notes.addWidget(self.scrollArea_notes)

        # TAB outlay
        self.tab_outlay = QtWidgets.QWidget(self.tabWidget_docx)
        self.tab_outlay.setObjectName("tab_outlay")
        self.vL_tab_outlay = QtWidgets.QVBoxLayout(self.tab_outlay)
        self.vL_tab_outlay.setObjectName("vL_tab_outlay")
        self.tabWidget_docx.addTab(self.tab_outlay, "")

        self.scrollArea_outlay = QtWidgets.QScrollArea(self.widget_docx)
        self.scrollArea_outlay.setWidgetResizable(True)
        self.scrollArea_outlay.setObjectName("scrollArea_outlay")
        self.sAWContent_outlay = QtWidgets.QWidget(self.tab_outlay)
        self.sAWContent_outlay.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_outlay.setObjectName("sAWContent_outlay")
        self.vL_sAWContent_outlay = QtWidgets.QVBoxLayout(self.sAWContent_outlay)
        self.vL_sAWContent_outlay.setObjectName("vL_sAWContent_outlay")
        self.scrollArea_outlay.setWidget(self.sAWContent_outlay)
        self.vL_tab_outlay.addWidget(self.scrollArea_outlay)

        # TAB ttable
        self.tab_ttable = QtWidgets.QWidget(self.tabWidget_docx)
        self.tab_ttable.setObjectName("tab_ttable")
        self.vL_tab_ttable = QtWidgets.QVBoxLayout(self.tab_ttable)
        self.vL_tab_ttable.setObjectName("vL_tab_ttable")
        self.tabWidget_docx.addTab(self.tab_ttable, "")

        self.scrollArea_ttable = QtWidgets.QScrollArea(self.widget_docx)
        self.scrollArea_ttable.setWidgetResizable(True)
        self.scrollArea_ttable.setObjectName("scrollArea_ttable")
        self.sAWContent_ttable = QtWidgets.QWidget(self.tab_ttable)
        self.sAWContent_ttable.setGeometry(QtCore.QRect(0, 0, 858, 372))
        self.sAWContent_ttable.setObjectName("sAWContent_ttable")
        self.vL_sAWContent_ttable = QtWidgets.QVBoxLayout(self.sAWContent_ttable)
        self.vL_sAWContent_ttable.setObjectName("vL_sAWContent_ttable")
        self.scrollArea_ttable.setWidget(self.sAWContent_ttable)
        self.vL_tab_ttable.addWidget(self.scrollArea_ttable)

        # Main setups
        self.vL_widget_Main.addWidget(self.tabWidget_Main)
        self.hL_mainwidget.addWidget(self.widget_Main)
        MainWindow.setCentralWidget(self.mainwidget)

        # MenuBar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)

        # Settings
        self.settings = QtWidgets.QAction(MainWindow)
        self.settings.setObjectName("settings")
        self.menu.addAction(self.settings)
        self.menubar.addAction(self.menu.menuAction())

        # Status Bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АРМ специалиста ЦПЮИ"))
        self.pushButton_headers_roster.setText(_translate("MainWindow", "Должностные лица"))
        self.pushButton_students_roster.setText(_translate("MainWindow", "Обучающиеся"))
        self.pushButton_subjects_roster.setText(_translate("MainWindow", "Предметы"))
        self.pushButton_programs_roster.setText(_translate("MainWindow", "Образовательные программы"))
        self.pushButton_teachers_roster.setText(_translate("MainWindow", "Преподаватели"))
        self.pushButton_outlay.setText(_translate("MainWindow", "Калькулятор Сметы"))
        self.pushButton_groups_roster.setText(_translate("MainWindow", "Группы"))
        self.pushButton_enrollment_roster.setText(_translate("MainWindow", "Зачисления"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_roster), _translate("MainWindow", "Реестр"))
        self.pushButton_edit_timetable.setText(_translate("MainWindow", "Изменить расписание"))
        self.pushButton_print_timetable.setText(_translate("MainWindow", "Сохранить как документ"))
        self.pushButton_update_timetable.setText(_translate("MainWindow", "Обновить список"))
        self.pushButton_update_docx.setText(_translate("MainWindow", "Обновить списки"))
        self.pushButton_del_docx.setText(_translate("MainWindow", "Удалить выбранный документ"))
        self.label_search_timetable.setText(_translate("MainWindow", "Поиск:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_timetable), _translate("MainWindow", "Расписание"))
        self.pushButton_create_docx.setText(_translate("MainWindow", "Создать новый документ"))
        self.pushButton_edit_docx.setText(_translate("MainWindow", "Редактировать выбранный документ"))
        self.pushButton_print_docx.setText(_translate("MainWindow", "Печать"))
        self.label_search_docx.setText(_translate("MainWindow", "Поиск:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_docx), _translate("MainWindow", "Документы"))
        self.tabWidget_docx.setTabText(self.tabWidget_docx.indexOf(self.tab_decree), _translate("MainWindow", "Приказы"))
        self.tabWidget_docx.setTabText(self.tabWidget_docx.indexOf(self.tab_notes), _translate("MainWindow", "Служебные записки"))
        self.tabWidget_docx.setTabText(self.tabWidget_docx.indexOf(self.tab_outlay), _translate("MainWindow", "Сметы"))
        self.tabWidget_docx.setTabText(self.tabWidget_docx.indexOf(self.tab_ttable), _translate("MainWindow", "Расписания"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
        self.settings.setText(_translate("MainWindow", "Почта"))
